# Copyright 2020-2022 Björn Kautler
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Setup WSL
description: WSL Setup GitHub Action
author: Björn Kautler

branding:
    icon: terminal
    color: purple

inputs:
    distribution:
        description: |
            The WSL distribution to install, update, or configure.
            'Ubuntu-22.04' and 'Ubuntu-20.04' can not be used together at the same time.
            They use the same WSL distribution ID, so the second that is used will not be installed
            as the first one will be found as already installed by WSL distribution ID.
            Valid values: 'Alpine', 'Debian', 'kali-linux', 'openSUSE-Leap-15.2', 'Ubuntu-24.04', 'Ubuntu-22.04', 'Ubuntu-20.04', 'Ubuntu-18.04', 'Ubuntu-16.04'
        required: false
        default: Debian

    use-cache:
        description: |
            Whether to use the cache for the downloaded distribution installer.
            This saves time in subsequent runs, jobs, or workflows but consumes space from
            the available cache space of the repository.
            Refer to https://github.com/marketplace/actions/cache for current usage limits.
            Default is 'true' if the cache feature is available.
            Default is 'false' if the cache feature is not available, for example because it was disabled on a GitHub Enterprise instance.
        required: false
        default: true | false

    wsl-conf:
        description: |
            The content that will be written to /etc/wsl.conf of the installed distribution.
            This can be used to adjust various settings as documented at
            https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configuration-settings-for-wslconf.
            This can also be used if the distribution is installed already.
        required: false

    set-as-default:
        description: |
            Whether to set the distribution as default WSL distribution.
            This can also be used if the distribution is installed already.
            Default is 'true' if the distribution is going to be installed.
            Default is 'false' if the distribution is only getting configured, updated, or additional packages installed.
            The first installed WSL distribution is automatically the default one, independently of this input.
        required: false
        default: true | false

    update:
        description: |
            Whether to update the distribution after installation.
            This can also be used if the distribution is installed already.
        required: false
        default: 'false'

    additional-packages:
        description: |
            Space separated list of additional packages to install after distribution installation.
            This can also be used if the distribution is installed already.
        required: false

    wsl-shell-user:
        description: |
            The distribution user that should be used to execute run-step scripts with wsl-shell wrapper scripts
            that are created or updated by the current action invocation. If no value is given, the default user of
            the distribution at script execution time is used.
        required: false

    wsl-shell-command:
        description: |
            The command that is used in the wsl-shell wrapper scripts to execute the run-step script.
            The name of the wrapper scripts will be derived from the first word in this input prefixed with 'wsl-'.
            This means that for the default value, the wrapper scripts will start with 'wsl-bash'.
            The run-step script file will be given as additional parameter in single quotes after the given string,
            separated with one space character. The latter point is important, if you need to escape this space character.
            If the given string contains at least once the sequence '{0}', all occurrences of it will be replaced by the
            run-step script file without any quotes or anything and it will not be given as additional parameter.
            This can be used if the script file is needed within the shell command opposed to as additional parameter.
            This input can also be used if the distribution is installed already to change the wrapper scripts or generate
            additional ones for other shells.
        required: false

    wsl-version:
        description: |
            The WSL version that should be used. This can be set to any positive integer. Using an untested one might
            work or break, so issues a warning for the action run. Currently, WSLv1 and WSLv2 are tested and do not
            issue a warning. If a new WSL version is available and your workflow works with it, please report an issue
            so that proper tests can be added and the warning for that version removed.
        required: false
        default: '2'

outputs:
    wsl-shell-wrapper-path:
        description: |
            The path to the wsl-shell wrapper that is generated by the current action invocation.
            Even if the current action invocation does not actually generate the script, because
            wsl-shell-command is not set explicitly and the script already exists, this output will be set.

    wsl-shell-distribution-wrapper-path:
        description: |
            The path to the distribution-specific wsl-shell wrapper that is generated by the current action invocation.
            Even if the current action invocation does not actually generate the script, because
            wsl-shell-command is not set explicitly and the script already exists, this output will be set.

runs:
    using: node20
    main: build/distributions/index.mjs
